// =============================================================================
// THIS FILE WAS GENERATED - DON'T EDIT IT
// GENERATED BY: ./bin/opcode-table-generator
//
// [Reference](https://en.wikipedia.org/wiki/MOS_Technology_6502#Instruction_table)
// =============================================================================

#ifndef OPCODE_TABLE_H
#define OPCODE_TABLE_H

#include "nes/op.h"

static const Op OPCODE_TABLE[256] = {
    // Column 0
    [0x00] = {OP_BRK,        ADDR_MODE_IMPLIED},        // BRK 
    [0x10] = {OP_BPL,        ADDR_MODE_RELATIVE},       // BPL rel
    [0x20] = {OP_JSR,        ADDR_MODE_ABSOLUTE},       // JSR abs
    [0x30] = {OP_BMI,        ADDR_MODE_RELATIVE},       // BMI rel
    [0x40] = {OP_RTI,        ADDR_MODE_IMPLIED},        // RTI 
    [0x50] = {OP_BVC,        ADDR_MODE_RELATIVE},       // BVC rel
    [0x60] = {OP_RTS,        ADDR_MODE_IMPLIED},        // RTS 
    [0x70] = {OP_BVS,        ADDR_MODE_RELATIVE},       // BVS rel
    [0x80] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x90] = {OP_BCC,        ADDR_MODE_RELATIVE},       // BCC rel
    [0xA0] = {OP_LDY,        ADDR_MODE_IMMEDIATE},      // LDY #imm
    [0xB0] = {OP_BCS,        ADDR_MODE_RELATIVE},       // BCS rel
    [0xC0] = {OP_CPY,        ADDR_MODE_IMMEDIATE},      // CPY #imm
    [0xD0] = {OP_BNE,        ADDR_MODE_RELATIVE},       // BNE rel
    [0xE0] = {OP_CPX,        ADDR_MODE_IMMEDIATE},      // CPX #imm
    [0xF0] = {OP_BEQ,        ADDR_MODE_RELATIVE},       // BEQ rel
    // Column 1
    [0x01] = {OP_ORA,        ADDR_MODE_INDIRECT_X},     // ORA (ind,X)
    [0x11] = {OP_ORA,        ADDR_MODE_INDIRECT_Y},     // ORA (ind),Y
    [0x21] = {OP_AND,        ADDR_MODE_INDIRECT_X},     // AND (ind,X)
    [0x31] = {OP_AND,        ADDR_MODE_INDIRECT_Y},     // AND (ind),Y
    [0x41] = {OP_EOR,        ADDR_MODE_INDIRECT_X},     // EOR (ind,X)
    [0x51] = {OP_EOR,        ADDR_MODE_INDIRECT_Y},     // EOR (ind),Y
    [0x61] = {OP_ADC,        ADDR_MODE_INDIRECT_X},     // ADC (ind,X)
    [0x71] = {OP_ADC,        ADDR_MODE_INDIRECT_Y},     // ADC (ind),Y
    [0x81] = {OP_STA,        ADDR_MODE_INDIRECT_X},     // STA (ind,X)
    [0x91] = {OP_STA,        ADDR_MODE_INDIRECT_Y},     // STA (ind),Y
    [0xA1] = {OP_LDA,        ADDR_MODE_INDIRECT_X},     // LDA (ind,X)
    [0xB1] = {OP_LDA,        ADDR_MODE_INDIRECT_Y},     // LDA (ind),Y
    [0xC1] = {OP_CMP,        ADDR_MODE_INDIRECT_X},     // CMP (ind,X)
    [0xD1] = {OP_CMP,        ADDR_MODE_INDIRECT_Y},     // CMP (ind),Y
    [0xE1] = {OP_SBC,        ADDR_MODE_INDIRECT_X},     // SBC (ind,X)
    [0xF1] = {OP_SBC,        ADDR_MODE_INDIRECT_Y},     // SBC (ind),Y
    // Column 2
    [0x02] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x12] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x22] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x32] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x42] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x52] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x62] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x72] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x82] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x92] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xA2] = {OP_LDX,        ADDR_MODE_IMMEDIATE},      // LDX #imm
    [0xB2] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xC2] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xD2] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xE2] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xF2] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column 3
    [0x03] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x13] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x23] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x33] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x43] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x53] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x63] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x73] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x83] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x93] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xA3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xB3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xC3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xD3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xE3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xF3] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column 4
    [0x04] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x14] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x24] = {OP_BIT,        ADDR_MODE_ZERO_PAGE},      // BIT zpg
    [0x34] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x44] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x54] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x64] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x74] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x84] = {OP_STY,        ADDR_MODE_ZERO_PAGE},      // STY zpg
    [0x94] = {OP_STY,        ADDR_MODE_ZERO_PAGE_X},    // STY zpg,X
    [0xA4] = {OP_LDY,        ADDR_MODE_ZERO_PAGE},      // LDY zpg
    [0xB4] = {OP_LDY,        ADDR_MODE_ZERO_PAGE_X},    // LDY zpg,X
    [0xC4] = {OP_CPY,        ADDR_MODE_ZERO_PAGE},      // CPY zpg
    [0xD4] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xE4] = {OP_CPX,        ADDR_MODE_ZERO_PAGE},      // CPX zpg
    [0xF4] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column 5
    [0x05] = {OP_ORA,        ADDR_MODE_ZERO_PAGE},      // ORA zpg
    [0x15] = {OP_ORA,        ADDR_MODE_ZERO_PAGE_X},    // ORA zpg,X
    [0x25] = {OP_AND,        ADDR_MODE_ZERO_PAGE},      // AND zpg
    [0x35] = {OP_AND,        ADDR_MODE_ZERO_PAGE_X},    // AND zpg,X
    [0x45] = {OP_EOR,        ADDR_MODE_ZERO_PAGE},      // EOR zpg
    [0x55] = {OP_EOR,        ADDR_MODE_ZERO_PAGE_X},    // EOR zpg,X
    [0x65] = {OP_ADC,        ADDR_MODE_ZERO_PAGE},      // ADC zpg
    [0x75] = {OP_ADC,        ADDR_MODE_ZERO_PAGE_X},    // ADC zpg,X
    [0x85] = {OP_STA,        ADDR_MODE_ZERO_PAGE},      // STA zpg
    [0x95] = {OP_STA,        ADDR_MODE_ZERO_PAGE_X},    // STA zpg,X
    [0xA5] = {OP_LDA,        ADDR_MODE_ZERO_PAGE},      // LDA zpg
    [0xB5] = {OP_LDA,        ADDR_MODE_ZERO_PAGE_X},    // LDA zpg,X
    [0xC5] = {OP_CMP,        ADDR_MODE_ZERO_PAGE},      // CMP zpg
    [0xD5] = {OP_CMP,        ADDR_MODE_ZERO_PAGE_X},    // CMP zpg,X
    [0xE5] = {OP_SBC,        ADDR_MODE_ZERO_PAGE},      // SBC zpg
    [0xF5] = {OP_SBC,        ADDR_MODE_ZERO_PAGE_X},    // SBC zpg,X
    // Column 6
    [0x06] = {OP_ASL,        ADDR_MODE_ZERO_PAGE},      // ASL zpg
    [0x16] = {OP_ASL,        ADDR_MODE_ZERO_PAGE_X},    // ASL zpg,X
    [0x26] = {OP_ROL,        ADDR_MODE_ZERO_PAGE},      // ROL zpg
    [0x36] = {OP_ROL,        ADDR_MODE_ZERO_PAGE_X},    // ROL zpg,X
    [0x46] = {OP_LSR,        ADDR_MODE_ZERO_PAGE},      // LSR zpg
    [0x56] = {OP_LSR,        ADDR_MODE_ZERO_PAGE_X},    // LSR zpg,X
    [0x66] = {OP_ROR,        ADDR_MODE_ZERO_PAGE},      // ROR zpg
    [0x76] = {OP_ROR,        ADDR_MODE_ZERO_PAGE_X},    // ROR zpg,X
    [0x86] = {OP_STX,        ADDR_MODE_ZERO_PAGE},      // STX zpg
    [0x96] = {OP_STX,        ADDR_MODE_ZERO_PAGE_Y},    // STX zpg,Y
    [0xA6] = {OP_LDX,        ADDR_MODE_ZERO_PAGE},      // LDX zpg
    [0xB6] = {OP_LDX,        ADDR_MODE_ZERO_PAGE_Y},    // LDX zpg,Y
    [0xC6] = {OP_DEC,        ADDR_MODE_ZERO_PAGE},      // DEC zpg
    [0xD6] = {OP_DEC,        ADDR_MODE_ZERO_PAGE_X},    // DEC zpg,X
    [0xE6] = {OP_INC,        ADDR_MODE_ZERO_PAGE},      // INC zpg
    [0xF6] = {OP_INC,        ADDR_MODE_ZERO_PAGE_X},    // INC zpg,X
    // Column 7
    [0x07] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x17] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x27] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x37] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x47] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x57] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x67] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x77] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x87] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x97] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xA7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xB7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xC7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xD7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xE7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xF7] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column 8
    [0x08] = {OP_PHP,        ADDR_MODE_IMPLIED},        // PHP 
    [0x18] = {OP_CLC,        ADDR_MODE_IMPLIED},        // CLC 
    [0x28] = {OP_PLP,        ADDR_MODE_IMPLIED},        // PLP 
    [0x38] = {OP_SEC,        ADDR_MODE_IMPLIED},        // SEC 
    [0x48] = {OP_PHA,        ADDR_MODE_IMPLIED},        // PHA 
    [0x58] = {OP_CLI,        ADDR_MODE_IMPLIED},        // CLI 
    [0x68] = {OP_PLA,        ADDR_MODE_IMPLIED},        // PLA 
    [0x78] = {OP_SEI,        ADDR_MODE_IMPLIED},        // SEI 
    [0x88] = {OP_DEY,        ADDR_MODE_IMPLIED},        // DEY 
    [0x98] = {OP_TYA,        ADDR_MODE_IMPLIED},        // TYA 
    [0xA8] = {OP_TAY,        ADDR_MODE_IMPLIED},        // TAY 
    [0xB8] = {OP_CLV,        ADDR_MODE_IMPLIED},        // CLV 
    [0xC8] = {OP_INY,        ADDR_MODE_IMPLIED},        // INY 
    [0xD8] = {OP_CLD,        ADDR_MODE_IMPLIED},        // CLD 
    [0xE8] = {OP_INX,        ADDR_MODE_IMPLIED},        // INX 
    [0xF8] = {OP_SED,        ADDR_MODE_IMPLIED},        // SED 
    // Column 9
    [0x09] = {OP_ORA,        ADDR_MODE_IMMEDIATE},      // ORA #imm
    [0x19] = {OP_ORA,        ADDR_MODE_ABSOLUTE_Y},     // ORA abs,Y
    [0x29] = {OP_AND,        ADDR_MODE_IMMEDIATE},      // AND #imm
    [0x39] = {OP_AND,        ADDR_MODE_ABSOLUTE_Y},     // AND abs,Y
    [0x49] = {OP_EOR,        ADDR_MODE_IMMEDIATE},      // EOR #imm
    [0x59] = {OP_EOR,        ADDR_MODE_ABSOLUTE_Y},     // EOR abs,Y
    [0x69] = {OP_ADC,        ADDR_MODE_IMMEDIATE},      // ADC #imm
    [0x79] = {OP_ADC,        ADDR_MODE_ABSOLUTE_Y},     // ADC abs,Y
    [0x89] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x99] = {OP_STA,        ADDR_MODE_ABSOLUTE_Y},     // STA abs,Y
    [0xA9] = {OP_LDA,        ADDR_MODE_IMMEDIATE},      // LDA #imm
    [0xB9] = {OP_LDA,        ADDR_MODE_ABSOLUTE_Y},     // LDA abs,Y
    [0xC9] = {OP_CMP,        ADDR_MODE_IMMEDIATE},      // CMP #imm
    [0xD9] = {OP_CMP,        ADDR_MODE_ABSOLUTE_Y},     // CMP abs,Y
    [0xE9] = {OP_SBC,        ADDR_MODE_IMMEDIATE},      // SBC #imm
    [0xF9] = {OP_SBC,        ADDR_MODE_ABSOLUTE_Y},     // SBC abs,Y
    // Column A
    [0x0A] = {OP_ASL,        ADDR_MODE_ACCUMULATOR},    // ASL A
    [0x1A] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x2A] = {OP_ROL,        ADDR_MODE_ACCUMULATOR},    // ROL A
    [0x3A] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x4A] = {OP_LSR,        ADDR_MODE_ACCUMULATOR},    // LSR A
    [0x5A] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x6A] = {OP_ROR,        ADDR_MODE_ACCUMULATOR},    // ROR A
    [0x7A] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x8A] = {OP_TXA,        ADDR_MODE_IMPLIED},        // TXA 
    [0x9A] = {OP_TXS,        ADDR_MODE_IMPLIED},        // TXS 
    [0xAA] = {OP_TAX,        ADDR_MODE_IMPLIED},        // TAX 
    [0xBA] = {OP_TSX,        ADDR_MODE_IMPLIED},        // TSX 
    [0xCA] = {OP_DEX,        ADDR_MODE_IMPLIED},        // DEX 
    [0xDA] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xEA] = {OP_NOP,        ADDR_MODE_IMPLIED},        // NOP 
    [0xFA] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column B
    [0x0B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x1B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x2B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x3B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x4B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x5B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x6B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x7B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x8B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x9B] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xAB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xBB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xCB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xDB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xEB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xFB] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column C
    [0x0C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x1C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x2C] = {OP_BIT,        ADDR_MODE_ABSOLUTE},       // BIT abs
    [0x3C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x4C] = {OP_JMP,        ADDR_MODE_ABSOLUTE},       // JMP abs
    [0x5C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x6C] = {OP_JMP,        ADDR_MODE_INDIRECT},       // JMP (ind)
    [0x7C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x8C] = {OP_STY,        ADDR_MODE_ABSOLUTE},       // STY abs
    [0x9C] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xAC] = {OP_LDY,        ADDR_MODE_ABSOLUTE},       // LDY abs
    [0xBC] = {OP_LDY,        ADDR_MODE_ABSOLUTE_X},     // LDY abs,X
    [0xCC] = {OP_CPY,        ADDR_MODE_ABSOLUTE},       // CPY abs
    [0xDC] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xEC] = {OP_CPX,        ADDR_MODE_ABSOLUTE},       // CPX abs
    [0xFC] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    // Column D
    [0x0D] = {OP_ORA,        ADDR_MODE_ABSOLUTE},       // ORA abs
    [0x1D] = {OP_ORA,        ADDR_MODE_ABSOLUTE_X},     // ORA abs,X
    [0x2D] = {OP_AND,        ADDR_MODE_ABSOLUTE},       // AND abs
    [0x3D] = {OP_AND,        ADDR_MODE_ABSOLUTE_X},     // AND abs,X
    [0x4D] = {OP_EOR,        ADDR_MODE_ABSOLUTE},       // EOR abs
    [0x5D] = {OP_EOR,        ADDR_MODE_ABSOLUTE_X},     // EOR abs,X
    [0x6D] = {OP_ADC,        ADDR_MODE_ABSOLUTE},       // ADC abs
    [0x7D] = {OP_ADC,        ADDR_MODE_ABSOLUTE_X},     // ADC abs,X
    [0x8D] = {OP_STA,        ADDR_MODE_ABSOLUTE},       // STA abs
    [0x9D] = {OP_STA,        ADDR_MODE_ABSOLUTE_X},     // STA abs,X
    [0xAD] = {OP_LDA,        ADDR_MODE_ABSOLUTE},       // LDA abs
    [0xBD] = {OP_LDA,        ADDR_MODE_ABSOLUTE_X},     // LDA abs,X
    [0xCD] = {OP_CMP,        ADDR_MODE_ABSOLUTE},       // CMP abs
    [0xDD] = {OP_CMP,        ADDR_MODE_ABSOLUTE_X},     // CMP abs,X
    [0xED] = {OP_SBC,        ADDR_MODE_ABSOLUTE},       // SBC abs
    [0xFD] = {OP_SBC,        ADDR_MODE_ABSOLUTE_X},     // SBC abs,X
    // Column E
    [0x0E] = {OP_ASL,        ADDR_MODE_ABSOLUTE},       // ASL abs
    [0x1E] = {OP_ASL,        ADDR_MODE_ABSOLUTE_X},     // ASL abs,X
    [0x2E] = {OP_ROL,        ADDR_MODE_ABSOLUTE},       // ROL abs
    [0x3E] = {OP_ROL,        ADDR_MODE_ABSOLUTE_X},     // ROL abs,X
    [0x4E] = {OP_LSR,        ADDR_MODE_ABSOLUTE},       // LSR abs
    [0x5E] = {OP_LSR,        ADDR_MODE_ABSOLUTE_X},     // LSR abs,X
    [0x6E] = {OP_ROR,        ADDR_MODE_ABSOLUTE},       // ROR abs
    [0x7E] = {OP_ROR,        ADDR_MODE_ABSOLUTE_X},     // ROR abs,X
    [0x8E] = {OP_STX,        ADDR_MODE_ABSOLUTE},       // STX abs
    [0x9E] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xAE] = {OP_LDX,        ADDR_MODE_ABSOLUTE},       // LDX abs
    [0xBE] = {OP_LDX,        ADDR_MODE_ABSOLUTE_Y},     // LDX abs,Y
    [0xCE] = {OP_DEC,        ADDR_MODE_ABSOLUTE},       // DEC abs
    [0xDE] = {OP_DEC,        ADDR_MODE_ABSOLUTE_X},     // DEC abs,X
    [0xEE] = {OP_INC,        ADDR_MODE_ABSOLUTE},       // INC abs
    [0xFE] = {OP_INC,        ADDR_MODE_ABSOLUTE_X},     // INC abs,X
    // Column F
    [0x0F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x1F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x2F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x3F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x4F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x5F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x6F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x7F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x8F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0x9F] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xAF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xBF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xCF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xDF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xEF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
    [0xFF] = {OP__UNDEFINED, ADDR_MODE__UNDEFINED},
};

#endif // OPCODE_TABLE_H
